# Generated by Django 5.0.1 on 2024-02-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='adress',
            field=models.TextField(blank=True),
        ),
    ]
