# Generated by Django 5.0.1 on 2024-02-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_alter_seller_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='pencentage_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.05, max_digits=5),
        ),
    ]
