# Generated by Django 5.0.1 on 2024-02-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supermarket',
            name='cnpj',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
