# Generated by Django 5.0.1 on 2024-02-07 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_alter_product_production_date'),
        ('sellers', '0002_alter_seller_adress'),
        ('supermarkets', '0002_alter_supermarket_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date_of_order', models.DateField(auto_now_add=True)),
                ('invoicing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sellers.seller')),
                ('supermarket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supermarkets.supermarket')),
            ],
        ),
    ]
