# Generated by Django 5.0.1 on 2024-02-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_product_remove_order_quantity_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoicing',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
