# Generated by Django 5.0.1 on 2024-02-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_invoicing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoicing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
