# Generated by Django 5.0.1 on 2024-02-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_barcode_image_alter_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode_image',
            field=models.ImageField(blank=True, upload_to='products/barcodes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True),
        ),
    ]
