# Generated by Django 5.0.1 on 2024-02-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_barcode_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lot',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
