# Generated by Django 5.0.1 on 2024-02-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
