# Generated by Django 5.0.1 on 2024-02-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='production_date',
            field=models.DateField(blank=True),
        ),
    ]
